Repository NiconiKimg/CookingSharp, pull requests merged in 2025-09, with the labels that each got.

#28 Chore(Architecture): Reestructurar solución a proyectos por capas.
  CookingSharp/CookingSharp.Application/Contracts/ICategoryRepository.cs
  CookingSharp/CookingSharp.Application/Contracts/IUserRepository.cs
  CookingSharp/CookingSharp.Application/CookingSharp.Application.csproj
  CookingSharp/CookingSharp.Application/DTOs/Category.cs
  CookingSharp/CookingSharp.Application/DTOs/User.cs
  CookingSharp/CookingSharp.Application/Services/CategoryService.cs
  CookingSharp/CookingSharp.Application/Services/UserService.cs
  CookingSharp/CookingSharp.Domain.Model/CookingSharp.Domain.Model.csproj
  CookingSharp/CookingSharp.Domain/Category.cs
  CookingSharp/CookingSharp.Domain/CookingSharp.Domain.csproj
  CookingSharp/CookingSharp.Domain/User.cs
  CookingSharp/CookingSharp.Infrastructure/Clients/CategoryApiClient.cs
  CookingSharp/CookingSharp.Infrastructure/Clients/UserApiClient.cs
  CookingSharp/CookingSharp.Infrastructure/CookingSharp.Infrastructure.csproj
  CookingSharp/CookingSharp.Infrastructure/Persistence/Repositories/InMemoryCategoryRepository.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Repositories/InMemoryUserRepository.cs
  CookingSharp/CookingSharp.WebAPI/CookingSharp.WebAPI.csproj
  CookingSharp/CookingSharp.WebAPI/Program.cs
  CookingSharp/CookingSharp.WindowsForms/CookingSharp.WindowsForms.csproj
  CookingSharp/CookingSharp.WindowsForms/Program.cs
  CookingSharp/CookingSharp.sln
Labels: chore, architecture

#30 Refactor: Fortalacer la Entidad User
  CookingSharp/CookingSharp.Application/Services/UserService.cs
  CookingSharp/CookingSharp.Domain/User.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Repositories/InMemoryUserRepository.cs
Labels: refactor, domain

#39 Feature: Creation of the DBcontext
  CookingSharp/CookingSharp.Application/CookingSharp.Application.csproj
  CookingSharp/CookingSharp.Domain/CookingSharp.Domain.csproj
  CookingSharp/CookingSharp.Infrastructure/CookingSharp.Infrastructure.csproj
  CookingSharp/CookingSharp.Infrastructure/Migrations/20250921185310_InitialCreate.Designer.cs
  CookingSharp/CookingSharp.Infrastructure/Migrations/20250921185310_InitialCreate.cs
  CookingSharp/CookingSharp.Infrastructure/Migrations/CookingSharpDbContextModelSnapshot.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Configurations/CategoryConfiguration.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Configurations/UserConfiguration.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/CookingSharpDbContext.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Repositories/EFCategoryRepository.cs
  CookingSharp/CookingSharp.Infrastructure/Persistence/Repositories/EFUserRepository.cs
  CookingSharp/CookingSharp.WebAPI/CookingSharp.WebAPI.csproj
  CookingSharp/CookingSharp.WebAPI/Program.cs
  CookingSharp/CookingSharp.WebAPI/appsettings.Development.json
  CookingSharp/CookingSharp.WindowsForms/CookingSharp.WindowsForms.csproj
  CookingSharp/CookingSharp.WindowsForms/CookingSharp.WindowsForms.csproj.user
  CookingSharp/CookingSharp.WindowsForms/Program.cs
Labels: feature
